- name: Extract archive
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
    - name: Extract the archive and set the owner/permissions
      unarchive:
        src: /usr/src/sysops/devops.zip
        dest: /opt/sysops/
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: "0744"