apiVersion: v1                                                                                                  
kind: Service                                                                                                   
metadata:                                                                                                       
  creationTimestamp: null                                                                                       
  labels:                                                                                                       
    app: nagios-deployment                                                                                      
  name: nagios-service                                                                                       
spec:                                                                                                           
  ports:                                                                                                        
  - port: 80                                                                                                    
    nodePort: 30008                                                                                             
    protocol: TCP                                                                                               
    targetPort: 80                                                                                              
  selector:                                                                                                     
    app: nagios-deployment                                                                                      
  type: NodePort                                                                                                
status:                                                                                                         
  loadBalancer: {} 

